<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('barang')->insert([
            [
                'nama' => 'Lihab Nomor 1 Rp. 250.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-1-Rp.-250.000',
                'harga' => '250000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


            [
                'nama' => 'Lihab Nomor 2 Rp. 200.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-2-Rp.-200.000',
                'harga' => '200000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 2 Rp. 350.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-2-Rp.-350.000',
                'harga' => '350000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'nama' => 'Lihab Nomor 1 Rp. 800.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-1-Rp.-800.000',
                'harga' => '800000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 3 Rp. 275.000',
                'tipe' => 'Nomor 3',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-3-Rp.-275.000',
                'harga' => '275000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 3 Rp. 350.000',
                'tipe' => 'Nomor 3',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-3-Rp.-350.000',
                'harga' => '350000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),

            ],
            [
                'nama' => 'Lamat Nomor 1 Rp. 1.200.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Lamat-Nomor-1-Rp-1.200.000',
                'harga' => '1200000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lamat1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 1 Rp. 400.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-1-Rp.-400.000',
                'harga' => '400000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 3 Rp. 500.000',
                'tipe' => 'Nomor 3',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-3-Rp.-500.000',
                'harga' => '500000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 1 Rp. 600.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-1-Rp.-600.000',
                'harga' => '600000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 2 Rp. 500.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-2-Rp.-500.000',
                'harga' => '500000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lamat Nomor 1 Rp. 800.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Lamat-Nomor-1-Rp.-800.000',
                'harga' => '800000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lamat1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'nama' => 'Lamat Nomor 2 Rp. 700.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lamat-Nomor-1-Rp-700.000',
                'harga' => '700000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lamat2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lihab Nomor 2 Rp. 700.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lihab-Nomor-2-Rp.-700.000',
                'harga' => '700000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lihab2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lamat Nomor 2 Rp. 1.000.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Lamat-Nomor-2-Rp-1.000.000',
                'harga' => '1000000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lamat2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lamat Nomor 3 Rp. 700.000',
                'tipe' => 'Nomor 3',
                'panjang' => '120',
                'lebar' => '190',
                'slug' => 'Lamat-Nomor-3-Rp-700.000',
                'harga' => '700000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lamat3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Lamat Nomor 3 Rp. 850.000',
                'tipe' => 'Nomor 3',
                'panjang' => '120',
                'lebar' => '190',
                'slug' => 'Lamat-Nomor-3-Rp-850.000',
                'harga' => '850000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'lamat3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kasur Nomor 1 Rp. 1.400.000',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Kasur-Nomor-1-Rp-1.400.000',
                'harga' => '1400000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'kasur1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kasur Nomor 2 Rp. 1.200.000',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Kasur-Nomor-2-Rp-1.200.000',
                'harga' => '1200000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'kasur2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Kasur Nomor 3 Rp. 800.000',
                'tipe' => 'Nomor 3',
                'panjang' => '120',
                'lebar' => '190',
                'slug' => 'Kasur-Nomor-3-Rp-800.000',
                'harga' => '800000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'kasur3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Bola Dunia Tebal 11 CM No.1',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Busa-Bola-Dunia-Tebal-11-CM-No-1',
                'harga' => '800000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'boladunia1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Bola Dunia Tebal 11 CM No.2',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Busa-Bola-Dunia-Tebal-11-CM-No-2',
                'harga' => '700000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'boladunia2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Bola Dunia Tebal 11 CM No.3',
                'tipe' => 'Nomor 3',
                'panjang' => '120',
                'lebar' => '190',
                'slug' => 'Busa-Bola-Dunia-Tebal-11-CM-No-3',
                'harga' => '550000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'boladunia3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Procella Tebal 11 CM No.1',
                'tipe' => 'Nomor 1',
                'panjang' => '180',
                'lebar' => '190',
                'slug' => 'Busa-Procella-Tebal-11-CM-No-1',
                'harga' => '750000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'procella1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Procella Tebal 11 CM No.2',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '190',
                'slug' => 'Busa-Procella-Tebal-11-CM-No-2',
                'harga' => '650000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'procella2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Procella Tebal 11 CM No.3',
                'tipe' => 'Nomor 3',
                'panjang' => '120',
                'lebar' => '190',
                'slug' => 'Busa-Procella-Tebal-11-CM-No-3',
                'harga' => '500000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'procella3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Hercules Tebal 18 CM sm 25 CM No.1',
                'tipe' => 'Nomor 1',
                'panjang' => '190',
                'lebar' => '200',
                'slug' => 'Busa Hercules Tebal 18 CM sm 25 CM No.1',
                'harga' => '1700000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'hercules1.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Hercules Tebal 18 CM sm 25 CM No.2',
                'tipe' => 'Nomor 2',
                'panjang' => '160',
                'lebar' => '200',
                'slug' => 'Busa Hercules Tebal 18 CM sm 25 CM No.2',
                'harga' => '1500000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'hercules2.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Busa Hercules Tebal 18 CM sm 25 CM No.3',
                'tipe' => 'Nomor 3',
                'panjang' => '120',
                'lebar' => '200',
                'slug' => 'Busa Hercules Tebal 18 CM sm 25 CM No.3',
                'harga' => '1300000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'hercules3.jpg',
                'kategori_id' => '1',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bantal Busa',
                'tipe' => '-',
                'panjang' => '-',
                'lebar' => '-',
                'slug' => 'Bantal-Busa',
                'harga' => '50000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'bantalbusa.jpg',
                'kategori_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bantal Dakron',
                'tipe' => '-',
                'panjang' => '-',
                'lebar' => '-',
                'slug' => 'Bantal-Dakron',
                'harga' => '80000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'bantaldakron.jpg',
                'kategori_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bantal Kapuk',
                'tipe' => '-',
                'panjang' => '-',
                'lebar' => '-',
                'slug' => 'Bantal-Kapuk',
                'harga' => '90000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'bantalkapuk.jpg',
                'kategori_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bantal Guling Busa',
                'tipe' => '-',
                'panjang' => '-',
                'lebar' => '-',
                'slug' => 'Bantal-Guling-Busa',
                'harga' => '55000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'gulingbusa.jpg',
                'kategori_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bantal Guling Dakron',
                'tipe' => '-',
                'panjang' => '-',
                'lebar' => '-',
                'slug' => 'Bantal-Guling-Dakron',
                'harga' => '85000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'gulingdakron.jpg',
                'kategori_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama' => 'Bantal Guling Kapuk',
                'tipe' => '-',
                'panjang' => '-',
                'lebar' => '-',
                'slug' => 'Bantal-Guling-Kapuk',
                'harga' => '95000',
                'in_stock' => '10',
                'sell_stock' => '0',
                'keterangan' => 'Tes',
                'foto' => 'gulingkapuk.jpg',
                'kategori_id' => '2',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
